[App.Jobs.Sub]
AddressToListen = "0x18Df82C7E422A42D47345Ed86B0E935E9718eBda"
EventName = "NumberChanged(uint256)"

[App.Jobs.Poller]
Interval = "1s"

[ConnectionPool]
EthHTTPURLs = ["http://localhost:10545"]
EthWSURLs = ["ws://localhost:10546"]
DefaultTimeout = "5s"

[Server.HTTP]
Port = 8080
